export const GET_ADDRESS_LIST_BY_USER_REQUEST = "GET_ADDRESS_LIST_BY_USER_REQUEST"
export const GET_ADDRESS_LIST_BY_USER_SUCCESS = "GET_ADDRESS_LIST_BY_USER_SUCCESS"
export const GET_ADDRESS_LIST_BY_USER_FAIL = "GET_ADDRESS_LIST_BY_USER_FAIL"

export const GET_ADDRESS_BY_USER_REQUEST = "GET_ADDRESS_BY_USER_REQUEST"
export const GET_ADDRESS_BY_USER_SUCCESS = "GET_ADDRESS_BY_USER_SUCCESS"
export const GET_ADDRESS_BY_USER_FAIL = "GET_ADDRESS_BY_USER_FAIL"

export const GET_CITY_LIST_REQUEST = "GET_CITY_LIST_REQUEST"
export const GET_CITY_LIST_SUCCESS = "GET_CITY_LIST_SUCCESS"
export const GET_CITY_LIST_FAIL = "GET_CITY_LIST_FAIL"

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL"

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST"
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS"
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL"
