export const GET_ADDRESS_LIST_BY_USER_REQUEST = "GET_ADDRESS_LIST_BY_USER_REQUEST"
export const GET_ADDRESS_LIST_BY_USER_SUCCESS = "GET_ADDRESS_LIST_BY_USER_SUCCESS"
export const GET_ADDRESS_LIST_BY_USER_FAIL = "GET_ADDRESS_LIST_BY_USER_FAIL"

export const GET_ADDRESS_BY_USER_REQUEST = "GET_ADDRESS_BY_USER_REQUEST"
export const GET_ADDRESS_BY_USER_SUCCESS = "GET_ADDRESS_BY_USER_SUCCESS"
export const GET_ADDRESS_BY_USER_FAIL = "GET_ADDRESS_BY_USER_FAIL"

export const GET_CITY_LIST_REQUEST = "GET_CITY_LIST_REQUEST"
export const GET_CITY_LIST_SUCCESS = "GET_CITY_LIST_SUCCESS"
export const GET_CITY_LIST_FAIL = "GET_CITY_LIST_FAIL"

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL"
export const ADD_ADDRESS_RESET = "ADD_ADDRESS_RESET"

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST"
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS"
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL"
export const UPDATE_ADDRESS_RESET = "UPDATE_ADDRESS_RESET"

export const GET_ADDRESS_BY_ID_REQUEST = "GET_ADDRESS_BY_ID_REQUEST"
export const GET_ADDRESS_BY_ID_SUCCESS = "GET_ADDRESS_BY_ID_SUCCESS"
export const GET_ADDRESS_BY_ID_FAIL = "GET_ADDRESS_BY_ID_FAIL"

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST"
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS"
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL"
