export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAIL = "GET_CART_FAIL"

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL"

export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
