export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAIL = "GET_CART_FAIL"

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL"

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST"
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS"
export const DELETE_CART_FAIL = "DELETE_CART_FAIL"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"

export const UPDATE_QTY_REQUEST = "UPDATE_QTY_REQUEST"
export const UPDATE_QTY_SUCCESS = "UPDATE_QTY_SUCCESS"
export const UPDATE_QTY_FAIL = "UPDATE_QTY_FAIL"

export const PUSH_CART_REQUEST = "PUSH_CART_REQUEST"
export const PUSH_CART_SUCCESS = "PUSH_CART_SUCCESS"
export const PUSH_CART_FAIL = "PUSH_CART_FAIL"
