export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET"

export const GET_ORDER_LIST_BY_USER_REQUEST = "GET_ORDER_LIST_BY_USER_REQUEST"
export const GET_ORDER_LIST_BY_USER_SUCCESS = "GET_ORDER_LIST_BY_USER_SUCCESS"
export const GET_ORDER_LIST_BY_USER_FAIL = "GET_ORDER_LIST_BY_USER_FAIL"

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST"
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS"
export const GET_ORDER_BY_ID_FAIL = "GET_ORDER_BY_ID_FAIL"

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST"
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS"
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL"
export const UPDATE_ORDER_STATUS_RESET = "UPDATE_ORDER_STATUS_RESET"

export const GET_ORDER_LIST_REQUEST = "GET_ORDER_LIST_REQUEST"
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS"
export const GET_ORDER_LIST_FAIL = "GET_ORDER_LIST_FAIL"

export const DELETE_ORDER_BY_ID_REQUEST = "DELETE_ORDER_BY_ID_REQUEST"
export const DELETE_ORDER_BY_ID_SUCCESS = "DELETE_ORDER_BY_ID_SUCCESS"
export const DELETE_ORDER_BY_ID_FAIL = "DELETE_ORDER_BY_ID_FAIL"
