export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAIL = "PRODUCT_LIST_REQUEST_FAIL";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS"
export const PRODUCT_REQUEST_FAIL = "PRODUCT_REQUEST_FAIL"

export const GET_SIMILARS_REQUEST = "GET_SIMILARS_REQUEST"
export const GET_SIMILARS_SUCCESS = "GET_SIMILARS_SUCCESS"
export const GET_SIMILARS_FAIL = "GET_SIMILARS_FAIL"
