export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAIL = "PRODUCT_LIST_REQUEST_FAIL";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS"
export const PRODUCT_REQUEST_FAIL = "PRODUCT_REQUEST_FAIL"

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL="UPDATE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_RESET="UPDATE_PRODUCT_RESET"

export const GET_SIMILARS_REQUEST = "GET_SIMILARS_REQUEST"
export const GET_SIMILARS_SUCCESS = "GET_SIMILARS_SUCCESS"
export const GET_SIMILARS_FAIL = "GET_SIMILARS_FAIL"

export const CREATE_RATING_REQUEST = "CREATE_RATING_REQUEST"
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS"
export const CREATE_RATING_FAIL = "CREATE_RATING_FAIL"

export const GET_USER_RATING_REQUEST = "GET_USER_RATING_REQUEST"
export const GET_USER_RATING_SUCCESS = "GET_USER_RATING_SUCCESS"
export const GET_USER_RATING_FAIL = "GET_USER_RATING_FAIL"

export const DELETE_PRODUCT_REQUEST ="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS ="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL ="DELETE_PRODUCT_FAIL"
export const DELETE_PRODUCT_RESET="DELETE_PRODUCT_RESET"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"

export const FUZZY_SEARCH_REQUEST = "FUZZY_SEARCH_REQUEST"
export const FUZZY_SEARCH_SUCCESS = "FUZZY_SEARCH_SUCCESS"
export const FUZZY_SEARCH_FAIL = "FUZZY_SEARCH_FAIL"

