export const BANNER_REQUEST = "BANNER_REQUEST"
export const BANNER_REQUEST_SUCCESS = "BANNER_REQUEST_SUCCESS"
export const BANNER_REQUEST_FAIL = "BANNER_REQUEST_FAIL"

export const RATING_LIST_BY_PRODUCT_REQUEST = "RATING_LIST_BY_PRODUCT_REQUEST"
export const RATING_LIST_BY_PRODUCT_REQUEST_SUCCESS = "RATING_LIST_BY_PRODUCT_REQUEST_SUCCESS"
export const RATING_LIST_BY_PRODUCT_REQUEST_FAIL = "RATING_LIST_BY_PRODUCT_REQUEST_FAIL"
