export const GET_WARRANTY_LIST_REQUEST = "GET_WARRANTY_LIST_REQUEST"
export const GET_WARRANTY_LIST_SUCCESS = "GET_WARRANTY_LIST_SUCCESS"
export const GET_WARRANTY_LIST_FAIL = "GET_WARRANTY_LIST_FAIL"
